# Generated by Django 4.1.2 on 2024-06-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=30, null=True, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
    ]
