# Generated by Django 4.1.2 on 2024-06-05 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
