# Generated by Django 5.0.6 on 2024-06-13 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_delete_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(db_column='idCiudad', primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='contrasena',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_ciudad',
            field=models.ForeignKey(db_column='idCiudad', default=1, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.ciudad'),
            preserve_default=False,
        ),
    ]
