# Generated by Django 5.0.6 on 2024-06-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_cliente_rut_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='id_ciudad',
            field=models.AutoField(db_column='idCiudad', primary_key=True, serialize=False),
        ),
    ]
