# Generated by Django 5.0.6 on 2024-06-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_alter_ciudad_id_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
