# Generated by Django 5.0.6 on 2024-06-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_cliente_contrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(max_length=50),
        ),
    ]
